source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'CoreParser_Example' do
  pod 'CoreParser', :path => '../'
end


target 'CoreParser_ExampleTests' do
    pod 'CoreParser', :path => '../'
end
